on:
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: run tests multiple times
        shell: bash
        run: |
          for i in $(seq 1 10); do
            cargo test -- --nocapture
          done
